name: Deploy main branch
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - staging
      - dev

env:
  _STAGE: dev
  _REPOSITORY_NAME: github-action-nodejs-serverless
jobs:
  DeployServerless:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm install
        run: npm install
      
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: serverless/github-action@master
        with:
          args: deploy --stage prod
        env:
          LOG_LEVEL: debug
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        uses: serverless/github-action@master
        with:
          args: deploy --stage staging
        env:
          LOG_LEVEL: debug
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to Development
        if: github.ref == 'refs/heads/dev'
        uses: serverless/github-action@master
        with:
          args: deploy --stage dev
        env:
          LOG_LEVEL: debug
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
